CREATE DATABASE IF NOT EXISTS soa_security_db;
CREATE DATABASE IF NOT EXISTS soa_payment_db;
CREATE DATABASE IF NOT EXISTS soa_listing_db;
CREATE DATABASE IF NOT EXISTS soa_sales_db;
CREATE DATABASE IF NOT EXISTS soa_rental_db;
