CREATE DATABASE IF NOT EXISTS soa_user_db;
CREATE DATABASE IF NOT EXISTS soa_transaction_db;
CREATE DATABASE IF NOT EXISTS soa_listing_db;
CREATE DATABASE IF NOT EXISTS soa_email_db;
CREATE DATABASE IF NOT EXISTS soa_subscription_db;
